POST http://localhost:3001/api/blogs HTTP/1.1
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZjczMTQyYjY1ZDhmODFmNWQ3NjQzMGIiLCJpYXQiOjE2MDEzNzk0MjJ9.d073V9u_gyxASNrvvRsytq_lVUIvAK3q0aOoZv-3t84

{
  "title": "Cool Post 22",
  "author": "Robert C. Martin",
  "url": "https://ismelich.tech/",
  "likes": "2",
  "userId": "5f73142b65d8f81f5d76430b"
}