POST http://localhost:3001/api/blogs HTTP/1.1
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ

{
  "title": "Cool Post 13",
  "author": "Robert C. Martin",
  "url": "https://ismelich.tech/",
  "likes": "3"
}