POST http://localhost:3001/api/blogs HTTP/1.1
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1Zjc0NTcyODljNmNjODE3ZWU5Y2JhYWMiLCJpYXQiOjE2MDE0NjAwMTJ9.92Vk-6wwVUpnEtwCCFnxHriG6faHQCQlEaJBBU9HpvM

{
  "title": "Cool Post 13",
  "author": "Robert C. Martin",
  "url": "https://ismelich.tech/",
  "likes": "3",
  "userId": "5f73142b65d8f81f5d76430b"
}